# Generated by Django 5.1.3 on 2025-01-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0002_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='category',
            new_name='catagory',
        ),
    ]
