# Generated by Django 5.1.3 on 2024-12-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0003_alter_stock_catagory_delete_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
