# Generated by Django 5.1.3 on 2024-12-31 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0004_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymgmt.catagory'),
        ),
    ]
