# Generated by Django 5.1.3 on 2024-12-31 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0007_catagory_alter_stock_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
        migrations.AlterField(
            model_name='stock',
            name='catagory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventorymgmt.catagory'),
        ),
    ]
