# Generated by Django 5.1.3 on 2024-12-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0009_stock_export_to_csv_alter_stock_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone'), ('Food', 'Food')], max_length=50, null=True),
        ),
    ]
