# Generated by Django 5.1.3 on 2025-01-01 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0010_alter_catagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
